language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
          - gcc-7
          - g++-7
          - cmake
          - lcov
          - libfftw3-dev
          - libsamplerate0-dev
          - libaudiofile-dev
          - libsndfile1-dev
          - libgtest-dev
          - libboost-all-dev
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
      env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

branches:
  only:
  - master

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

notifications:
  email: false

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./travis.sh

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash)
